/**
 * Configuração dos Tribunais Regionais do Trabalho (TRTs 1 a 24) e TST
 * Dados oficiais de jurisdição, URLs dos portais, PJe 1º Grau, PJe 2º Grau e Balcão Virtual.
 */

export const TRT_LIST = [
  {
    id: 'trt1',
    numero: 1,
    nome: 'TRT 1ª Região',
    uf: 'RJ',
    estado: 'Rio de Janeiro',
    regiao: 'Sudeste',
    descricao: 'Jurisdição sobre o Estado do Rio de Janeiro',
    pje1g: 'https://pje.trt1.jus.br/pjekz/',
    pje2g: 'https://pje.trt1.jus.br/pje-2g/',
    portal: 'https://www.trt1.jus.br/',
    balcaoVirtual: 'https://www.trt1.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt1.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt2',
    numero: 2,
    nome: 'TRT 2ª Região',
    uf: 'SP',
    estado: 'São Paulo (Capital e Baixada Santista)',
    regiao: 'Sudeste',
    descricao: 'Jurisdição sobre a Grande SP e Baixada Santista',
    pje1g: 'https://pje.trt2.jus.br/pjekz/',
    pje2g: 'https://pje.trt2.jus.br/pje-2g/',
    portal: 'https://ww2.trt2.jus.br/',
    balcaoVirtual: 'https://ww2.trt2.jus.br/servicos/balcao-virtual',
    consultaProcessual: 'https://ww2.trt2.jus.br/processos/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt3',
    numero: 3,
    nome: 'TRT 3ª Região',
    uf: 'MG',
    estado: 'Minas Gerais',
    regiao: 'Sudeste',
    descricao: 'Jurisdição sobre o Estado de Minas Gerais',
    pje1g: 'https://pje.trt3.jus.br/pjekz/',
    pje2g: 'https://pje.trt3.jus.br/pje-2g/',
    portal: 'https://portal.trt3.jus.br/',
    balcaoVirtual: 'https://portal.trt3.jus.br/balcao-virtual',
    consultaProcessual: 'https://portal.trt3.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt4',
    numero: 4,
    nome: 'TRT 4ª Região',
    uf: 'RS',
    estado: 'Rio Grande do Sul',
    regiao: 'Sul',
    descricao: 'Jurisdição sobre o Estado do Rio Grande do Sul',
    pje1g: 'https://pje.trt4.jus.br/pjekz/',
    pje2g: 'https://pje.trt4.jus.br/pje-2g/',
    portal: 'https://www.trt4.jus.br/',
    balcaoVirtual: 'https://www.trt4.jus.br/portais/trt4/balcao-virtual',
    consultaProcessual: 'https://www.trt4.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt5',
    numero: 5,
    nome: 'TRT 5ª Região',
    uf: 'BA',
    estado: 'Bahia',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado da Bahia',
    pje1g: 'https://pje.trt5.jus.br/pjekz/',
    pje2g: 'https://pje.trt5.jus.br/pje-2g/',
    portal: 'https://www.trt5.jus.br/',
    balcaoVirtual: 'https://www.trt5.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt5.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt6',
    numero: 6,
    nome: 'TRT 6ª Região',
    uf: 'PE',
    estado: 'Pernambuco',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado de Pernambuco',
    pje1g: 'https://pje.trt6.jus.br/pjekz/',
    pje2g: 'https://pje.trt6.jus.br/pje-2g/',
    portal: 'https://www.trt6.jus.br/',
    balcaoVirtual: 'https://www.trt6.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt6.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt7',
    numero: 7,
    nome: 'TRT 7ª Região',
    uf: 'CE',
    estado: 'Ceará',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado do Ceará',
    pje1g: 'https://pje.trt7.jus.br/pjekz/',
    pje2g: 'https://pje.trt7.jus.br/pje-2g/',
    portal: 'https://www.trt7.jus.br/',
    balcaoVirtual: 'https://www.trt7.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt7.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt8',
    numero: 8,
    nome: 'TRT 8ª Região',
    uf: 'PA/AP',
    estado: 'Pará e Amapá',
    regiao: 'Norte',
    descricao: 'Jurisdição sobre os Estados do Pará e Amapá',
    pje1g: 'https://pje.trt8.jus.br/pjekz/',
    pje2g: 'https://pje.trt8.jus.br/pje-2g/',
    portal: 'https://www.trt8.jus.br/',
    balcaoVirtual: 'https://www.trt8.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt8.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt9',
    numero: 9,
    nome: 'TRT 9ª Região',
    uf: 'PR',
    estado: 'Paraná',
    regiao: 'Sul',
    descricao: 'Jurisdição sobre o Estado do Paraná',
    pje1g: 'https://pje.trt9.jus.br/pjekz/',
    pje2g: 'https://pje.trt9.jus.br/pje-2g/',
    portal: 'https://www.trt9.jus.br/',
    balcaoVirtual: 'https://www.trt9.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt9.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt10',
    numero: 10,
    nome: 'TRT 10ª Região',
    uf: 'DF/TO',
    estado: 'Distrito Federal e Tocantins',
    regiao: 'Centro-Oeste',
    descricao: 'Jurisdição sobre o DF e Estado do Tocantins',
    pje1g: 'https://pje.trt10.jus.br/pjekz/',
    pje2g: 'https://pje.trt10.jus.br/pje-2g/',
    portal: 'https://www.trt10.jus.br/',
    balcaoVirtual: 'https://www.trt10.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt10.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt11',
    numero: 11,
    nome: 'TRT 11ª Região',
    uf: 'AM/RR',
    estado: 'Amazonas e Roraima',
    regiao: 'Norte',
    descricao: 'Jurisdição sobre os Estados do Amazonas e Roraima',
    pje1g: 'https://pje.trt11.jus.br/pjekz/',
    pje2g: 'https://pje.trt11.jus.br/pje-2g/',
    portal: 'https://www.trt11.jus.br/',
    balcaoVirtual: 'https://www.trt11.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt11.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt12',
    numero: 12,
    nome: 'TRT 12ª Região',
    uf: 'SC',
    estado: 'Santa Catarina',
    regiao: 'Sul',
    descricao: 'Jurisdição sobre o Estado de Santa Catarina',
    pje1g: 'https://pje.trt12.jus.br/pjekz/',
    pje2g: 'https://pje.trt12.jus.br/pje-2g/',
    portal: 'https://www.trt12.jus.br/',
    balcaoVirtual: 'https://www.trt12.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt12.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt13',
    numero: 13,
    nome: 'TRT 13ª Região',
    uf: 'PB',
    estado: 'Paraíba',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado da Paraíba',
    pje1g: 'https://pje.trt13.jus.br/pjekz/',
    pje2g: 'https://pje.trt13.jus.br/pje-2g/',
    portal: 'https://www.trt13.jus.br/',
    balcaoVirtual: 'https://www.trt13.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt13.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt14',
    numero: 14,
    nome: 'TRT 14ª Região',
    uf: 'RO/AC',
    estado: 'Rondônia e Acre',
    regiao: 'Norte',
    descricao: 'Jurisdição sobre os Estados de Rondônia e Acre',
    pje1g: 'https://pje.trt14.jus.br/pjekz/',
    pje2g: 'https://pje.trt14.jus.br/pje-2g/',
    portal: 'https://www.trt14.jus.br/',
    balcaoVirtual: 'https://www.trt14.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt14.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt15',
    numero: 15,
    nome: 'TRT 15ª Região',
    uf: 'SP',
    estado: 'São Paulo (Interior e Litoral Norte)',
    regiao: 'Sudeste',
    descricao: 'Jurisdição sobre Campinas e Interior de São Paulo',
    pje1g: 'https://pje.trt15.jus.br/pjekz/',
    pje2g: 'https://pje.trt15.jus.br/pje-2g/',
    portal: 'https://trt15.jus.br/',
    balcaoVirtual: 'https://trt15.jus.br/balcao-virtual',
    consultaProcessual: 'https://trt15.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt16',
    numero: 16,
    nome: 'TRT 16ª Região',
    uf: 'MA',
    estado: 'Maranhão',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado do Maranhão',
    pje1g: 'https://pje.trt16.jus.br/pjekz/',
    pje2g: 'https://pje.trt16.jus.br/pje-2g/',
    portal: 'https://www.trt16.jus.br/',
    balcaoVirtual: 'https://www.trt16.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt16.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt17',
    numero: 17,
    nome: 'TRT 17ª Região',
    uf: 'ES',
    estado: 'Espírito Santo',
    regiao: 'Sudeste',
    descricao: 'Jurisdição sobre o Estado do Espírito Santo',
    pje1g: 'https://pje.trt17.jus.br/pjekz/',
    pje2g: 'https://pje.trt17.jus.br/pje-2g/',
    portal: 'https://www.trt17.jus.br/',
    balcaoVirtual: 'https://www.trt17.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt17.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt18',
    numero: 18,
    nome: 'TRT 18ª Região',
    uf: 'GO',
    estado: 'Goiás',
    regiao: 'Centro-Oeste',
    descricao: 'Jurisdição sobre o Estado de Goiás',
    pje1g: 'https://pje.trt18.jus.br/pjekz/',
    pje2g: 'https://pje.trt18.jus.br/pje-2g/',
    portal: 'https://www.trt18.jus.br/',
    balcaoVirtual: 'https://www.trt18.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt18.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt19',
    numero: 19,
    nome: 'TRT 19ª Região',
    uf: 'AL',
    estado: 'Alagoas',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado de Alagoas',
    pje1g: 'https://pje.trt19.jus.br/pjekz/',
    pje2g: 'https://pje.trt19.jus.br/pje-2g/',
    portal: 'https://site.trt19.jus.br/',
    balcaoVirtual: 'https://site.trt19.jus.br/balcao-virtual',
    consultaProcessual: 'https://site.trt19.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt20',
    numero: 20,
    nome: 'TRT 20ª Região',
    uf: 'SE',
    estado: 'Sergipe',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado de Sergipe',
    pje1g: 'https://pje.trt20.jus.br/pjekz/',
    pje2g: 'https://pje.trt20.jus.br/pje-2g/',
    portal: 'https://www.trt20.jus.br/',
    balcaoVirtual: 'https://www.trt20.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt20.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt21',
    numero: 21,
    nome: 'TRT 21ª Região',
    uf: 'RN',
    estado: 'Rio Grande do Norte',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado do Rio Grande do Norte',
    pje1g: 'https://pje.trt21.jus.br/pjekz/',
    pje2g: 'https://pje.trt21.jus.br/pje-2g/',
    portal: 'https://www.trt21.jus.br/',
    balcaoVirtual: 'https://www.trt21.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt21.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt22',
    numero: 22,
    nome: 'TRT 22ª Região',
    uf: 'PI',
    estado: 'Piauí',
    regiao: 'Nordeste',
    descricao: 'Jurisdição sobre o Estado do Piauí',
    pje1g: 'https://pje.trt22.jus.br/pjekz/',
    pje2g: 'https://pje.trt22.jus.br/pje-2g/',
    portal: 'https://www.trt22.jus.br/',
    balcaoVirtual: 'https://www.trt22.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt22.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt23',
    numero: 23,
    nome: 'TRT 23ª Região',
    uf: 'MT',
    estado: 'Mato Grosso',
    regiao: 'Centro-Oeste',
    descricao: 'Jurisdição sobre o Estado de Mato Grosso',
    pje1g: 'https://pje.trt23.jus.br/pjekz/',
    pje2g: 'https://pje.trt23.jus.br/pje-2g/',
    portal: 'https://ww2.trt23.jus.br/',
    balcaoVirtual: 'https://ww2.trt23.jus.br/balcao-virtual',
    consultaProcessual: 'https://ww2.trt23.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'trt24',
    numero: 24,
    nome: 'TRT 24ª Região',
    uf: 'MS',
    estado: 'Mato Grosso do Sul',
    regiao: 'Centro-Oeste',
    descricao: 'Jurisdição sobre o Estado de Mato Grosso do Sul',
    pje1g: 'https://pje.trt24.jus.br/pjekz/',
    pje2g: 'https://pje.trt24.jus.br/pje-2g/',
    portal: 'https://www.trt24.jus.br/',
    balcaoVirtual: 'https://www.trt24.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.trt24.jus.br/consulta-processual',
    ativo: true,
  },
  {
    id: 'tst',
    numero: 0,
    nome: 'TST - Tribunal Superior do Trabalho',
    uf: 'BR',
    estado: 'Nacional',
    regiao: 'Nacional',
    descricao: 'Instância máxima da Justiça do Trabalho no Brasil',
    pje1g: 'https://pje.tst.jus.br/pje/',
    pje2g: 'https://pje.tst.jus.br/pje/',
    portal: 'https://www.tst.jus.br/',
    balcaoVirtual: 'https://www.tst.jus.br/balcao-virtual',
    consultaProcessual: 'https://www.tst.jus.br/processos-tst',
    ativo: true,
  }
];

export const REGIOES = ['Todas', 'Sudeste', 'Sul', 'Nordeste', 'Norte', 'Centro-Oeste', 'Nacional'];

export const CATEGORIAS_LINK = [
  { id: 'pje1g', label: 'PJe 1º Grau', icon: 'FileText' },
  { id: 'pje2g', label: 'PJe 2º Grau', icon: 'Layers' },
  { id: 'portal', label: 'Portal Oficial', icon: 'Globe' },
  { id: 'balcao', label: 'Balcão Virtual', icon: 'Video' },
  { id: 'consulta', label: 'Consulta Processual', icon: 'Search' },
  { id: 'personalizado', label: 'Personalizado', icon: 'Bookmark' }
];
